#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5'
bspc rule -a firefox desktop='^6'
bspc rule -a terminator desktop='1^'
bspc rule -a code desktop='^2'
bspc rule -a Screenkey manage=off

# wallpaper
feh --bg-fill /home/glow/Imágenes/wall/nasa.png

# bateria
sudo tlp start

# barra de estado superior
~/.config/polybar/./launch.sh

# seguimiento del raton
bspc config focus_follows_pointer true

# redondeado de las esquinas
picom --experimental-backends &
bspc config border_width 2
